server:
  disable: true

positions:
  filename: loki-positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system

    pipeline_stages:
      - docker: {}

    static_configs:
      - labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log
